import cPanel from "../../../assets/cPanel.png"
import Responsive from "../../../assets/Responsive.png"
import UX from "../../../assets/UX.png"
import security from "../../../assets/security.png"
import SEO from "../../../assets/SEO.png"
import bestPrice from "../../../assets/bestPrice.png"
import maintenance from "../../../assets/maintenance.png";
import tecSupport from "../../../assets/tecSupport.png";
import credibilityWork from "../../../assets/credibilityWork.png"
import increasesTraffic from "../../../assets/increasesTraffic.png"
import localEfforts from "../../../assets/localEfforts.png"
import longSuccess from "../../../assets/longSuccess.png"
import userExperience from "../../../assets/userExperience.png"
import Strategy from "../../../assets/Strategy.png"
import brandAwareness from "../../../assets/brandAwareness.png"
import Sales from "../../../assets/Sales.png"
import salesRates from "../../../assets/salesRates.png"
import eCommerceSales from "../../../assets/eCommerceSales.png"
import informedDecisions from "../../../assets/informedDecisions.png"
import EnhancesExperience from "../../../assets/EnhancesExperience.png"
import ReducesCopy from "../../../assets/ReducesCopy.png"
import ProvideConsistency from "../../../assets/ProvideConsistency.png"
import Lighting from "../../../assets/Lighting.png"
import CameraEquipment from "../../../assets/CameraEquipment.png"
import ProfessionalGrowth from "../../../assets/ProfessionalGrowth.png"
import RecognitionImpact from "../../../assets/RecognitionImpact.png"
import BrandingConsistency from "../../../assets/BrandingConsistency.png"
import EnhancedCommunication from "../../../assets/EnhancedCommunication.png"
import DifferentiationCompetitors from "../../../assets/DifferentiationCompetitors.png"
import IncreasedEngagement from "../../../assets/IncreasedEngagement.png"
import CostTime from "../../../assets/CostTime.png"
import FlexibilityAdaptability from "../../../assets/FlexibilityAdaptability.png"
import BuildingRelationships from "../../../assets/BuildingRelationships.png"
import IdentifyAudience from "../../../assets/IdentifyAudience.png"
import generateIdeas from "../../../assets/generateIdeas.png"
import DevelopContent from "../../../assets/DevelopContent.png"
import IncreaseAwareness from "../../../assets/IncreaseAwareness.png"
import ReuseContent from "../../../assets/ReuseContent.png"
import CostStrategy from "../../../assets/CostStrategy.png"
import IncreaseAcquisition from "../../../assets/IncreaseAcquisition.png"
import HigherConversion from "../../../assets/HigherConversion.png"
import ImprovedPerformance from "../../../assets/ImprovedPerformance.png"
import DirectAudience from "../../../assets/DirectAudience.png"
import MeasurePerformance from "../../../assets/MeasurePerformance.png"
import SponsoredVideo from "../../../assets/SponsoredVideo.png"
import BoostingImage from "../../../assets/BoostingImage.png"
import TrustCredibility from "../../../assets/TrustCredibility.png"





const items = [
{
    id: "SoftwareEngineering",
    "checkTitle": "Software engineering services:",
    "checkTitle_ar": "خدمات هندسة البرمجيات",
    "primaryItem": "User experience:",
    "primaryItem_ar": "تجربة المستخدم:",
    "secondaryItem": 'Working on the design Analyze the user experience It takes into account the requirements, preferences and observations of target users to create a user experience that meets their expectations.',
    "secondaryItem_ar": ".بعمل على تصميم  وتحليل تجربة المستخدم و نأخذ فى الاعتبار احتياجات وتفضيلات المستخدمين المستهدفين ودمج ملاحظتهم لانشاء تجربة مستخدم تلبى توقعاتهم",
    "primaryItem2": "Security and privacy:",
    "primaryItem2_ar": "الأمان والخصوصية:",
    "secondaryItem2": "Focus on protecting data and systems from unauthorized access, breaches, and cyber threats and implementing robust security measures and respecting privacy rights to create a secure and trustworthy environment for our customers.",
    "secondaryItem2_ar": "بركز على حماية البيانات والأنظمة من الوصول غير المصرح به والانتهاكات والتهديدات السيبرانية وتنفيذ تدابير أمنية قوية واحترام حقوق الخصوصية لخلق بيئة آمنة وجديرة بالثقة لعملائنا.",
    "primaryItem3": "SEO optimization:",
    "primaryItem3_ar": "تحسين محركات البحث:",
    "secondaryItem3": "practice of improving a website's visibility and ranking on search engine results pages (SERPs). improve the user experience by making websites more accessible, user-friendly, and relevant to search queries.",
    "secondaryItem3_ar": "ممارسة تحسين رؤية موقع الويب وتصنيفه على صفحات نتائج محرك البحث (SERPs). بعمل على تحسين تجربة المستخدم من خلال جعل مواقع الويب أكثر سهولة في الوصول إليها، وسهلة الاستخدام، وذات صلة باستعلامات البحث.",
    "primaryItem4": "Easy to use control panel:",
    "primaryItem4_ar": "لوحة تحكم سهلة الاستخدام:",
    "secondaryItem4": "This step involves creating and organizing the website's content, including text, images, videos, and other media. It is important to ensure that the content is engaging, informative, and aligned with the website's goals and target audience.",
    "secondaryItem4_ar": "تتضمن هذه الخطوة إنشاء وتنظيم محتوى موقع الويب، بما في ذلك النصوص والصور ومقاطع الفيديو والوسائط الأخرى. من المهم التأكد من أن المحتوى جذاب وغني بالمعلومات ومتوافق مع أهداف الموقع والجمهور المستهدف",
    "primaryItem5": "Responsive and compatible with mobile:",
    "primaryItem5_ar": "مستجيب و متوافق مع الجوال:",
    "secondaryItem5": "I Consider using device emulators or responsive design testing tools to simulate different devices.",
    "secondaryItem5_ar": "​​بفكر في استخدام محاكيات الأجهزة أو أدوات اختبار التصميم سريع الاستجابة لمحاكاة الأجهزة المختلفة.",
    "primaryItem6": "best price:",
    "primaryItem6_ar": "افضل الاسعار:",
    "secondaryItem6": "I provide diverse choices of products.",
    "secondaryItem6_ar": "بوفر خيارات متنوعة من المنتجات بافضل الاسعار",
    "primaryItem7": "Technical Support:",
    "primaryItem7_ar": "دعم فنى:",
    "secondaryItem7": "Once the website has been thoroughly tested and approved, it is ready for launch. This involves deploying the website to a live server, configuring domain and hosting settings, and making it accessible to the public.",
    "secondaryItem7_ar": 'من الأفضل دائمًا الحصول على معلومات أكثر دقة وحداثة حول الوصول إلى دعم فني مواكب مع احدث تطورات العصر.',
    "primaryItem8": "Maintenance:",
    "primaryItem8_ar": "الصيانة:",
    "secondaryItem8": "Website maintenance involves ongoing updates, security monitoring, bug fixes, and content management. Regularly updating the website's software, plugins, and security measures helps ensure its optimal performance and protection against vulnerabilities.",
    "secondaryItem8_ar": "تتضمن صيانة مواقع الويب التحديثات المستمرة ومراقبة الأمان وإصلاحات الأخطاء وإدارة المحتوى. يساعد التحديث المنتظم لبرامج الموقع الإلكتروني والمكونات الإضافية وإجراءات الأمان على ضمان الأداء الأمثل والحماية من الثغرات الأمنية.",
    itemIcon1: <img className="w-full h-full" src={UX} alt="UX" />,
    itemIcon2: <img className="w-full h-full" src={security} alt="security" />,
    itemIcon3: <img className="w-full h-full" src={SEO} alt="SEO" />,
    itemIcon4: <img className="w-full h-full" src={cPanel} alt="control-panel" />,
    itemIcon5: <img className="w-full h-full" src={Responsive} alt="Responsive" />,
    itemIcon6: <img className="w-full h-full" src={bestPrice} alt="Best Price" />,
    itemIcon7: <img className="w-full h-full" src={tecSupport} alt="Technical Support" />,
    itemIcon8: <img className="w-full h-full" src={maintenance} alt="maintenance" />,
    "reMaintenanceService": "Maintenance",
    "reMaintenanceService_ar": "صيانة",
  },
  {
    id: "SEOoptimization",
    "checkTitle": "SEO optimization services:",
    "checkTitle_ar": "خدمات تحسين نتائج البحث",
    "primaryItem": "Credibility of work:",
    "primaryItem_ar": ":تعزيز مصداقية عملك",
    "secondaryItem": 'A website that ranks high on search engine results pages is often considered trustworthy and of high quality by search engines. This boosts the credibility of your business.',
    "secondaryItem_ar": "غالبًا ما يعتبر موقع الويب الذي يحتل مرتبة عالية في صفحات نتائج محرك البحث جديرًا بالثقة وذو جودة عالية من قبل محركات البحث. وهذا يعزز مصداقية عملك",
    "primaryItem2": "Increases Web Traffic:",
    "primaryItem2_ar": "يزيد من حركة المرور على شبكة الإنترنت",
    "secondaryItem2": "I help improve your website's visibility in search engine results, leading to increased organic web traffic. Higher visibility means more potential customers discovering your business.",
    "secondaryItem2_ar": "بساعد ​​على تحسين ظهور موقع الويب الخاص بك في نتائج محرك البحث، مما يؤدي إلى زيادة حركة المرور على الويب. إن الرؤية الأعلى تعني المزيد من العملاء المحتملين الذين يكتشفون عملك.",
    "primaryItem3": "Enhances Brand Awareness:",
    "primaryItem3_ar": "يعزز الوعي بالعلامة التجارية:",
    "secondaryItem3": "I help in getting a higher ranking in search results and increases the exposure of your website, leading to increased brand awareness. Trustworthy.",
    "secondaryItem3_ar": "​​بساعد في الحصول على تصنيف أعلى في نتائج البحث و يزيد من عرض موقع الويب الخاص بك، مما يؤدي إلى زيادة الوعي بالعلامة التجارية. بالجدارة بالثقة.",
    "primaryItem4": "Improves User Experience:",
    "primaryItem4_ar": "تحسين تجربة المستخدم:",
    "secondaryItem4": "I improve the user experience by making your website more user-friendly, faster and easier to navigate.",
    "secondaryItem4_ar": "بعمل على تحسين تجربة المستخدم من خلال جعل موقع الويب الخاص بك أكثر سهولة في الاستخدام وأسرع وأسهل في التنقل.",
    "primaryItem5": "Generates Leads and Sales:",
    "primaryItem5_ar": "يولد العملاء المحتملين والمبيعات:",
    "secondaryItem5": "Average solution can significantly impact lead generation and sales. By increasing your website's visibility and attracting relevant traffic, you have a higher chance of converting visitors into customers.",
    "secondaryItem5_ar": "يمكن أن يؤثر الحل المعدل ​​بشكل كبير على توليد العملاء المحتملين والمبيعات. من خلال زيادة ظهور موقع الويب الخاص بك وجذب حركة المرور ذات الصلة، لديك فرصة أكبر لتحويل الزوار إلى عملاء.",
    "primaryItem6": "Strengthens Digital Marketing Strategy:",
    "primaryItem6_ar": "تعزيز استراتيجية التسويق الرقمي:",
    "secondaryItem6": "I work in synergy with other digital marketing strategies, such as content marketing and social media marketing. By incorporating SEO into your overall marketing strategy, you can maximize its effectiveness.",
    "secondaryItem6_ar": "يعمل الحل المعدل ​​بالتآزر مع استراتيجيات التسويق الرقمي الأخرى، مثل تسويق المحتوى والتسويق عبر وسائل التواصل الاجتماعي. من خلال دمج تحسين محركات البحث (SEO) في استراتيجية التسويق العامة الخاصة بك، يمكنك زيادة فعاليتها إلى أقصى حد.",
    "primaryItem7": "Improves Local Marketing Efforts:",
    "primaryItem7_ar": "تحسين جهود التسويق المحلية:",
    "secondaryItem7": "I help businesses target customers in specific geographic areas. This is particularly beneficial for businesses with physical locations or those targeting a local customer base.",
    "secondaryItem7_ar": 'بساعد ​​الشركات على استهداف العملاء في مناطق جغرافية محددة. وهذا مفيد بشكل خاص للشركات التي لها مواقع فعلية أو تلك التي تستهدف قاعدة عملاء محلية.',
    "primaryItem8": "Long-Term Success:",
    "primaryItem8_ar": "النجاح على المدى الطويل:",
    "secondaryItem8": "I optimize your website and stays on top of search engine algorithms, and you can maintain and improve your search rankings over time.",
    "secondaryItem8_ar": "​​بعمل على تحسين موقع الويب الخاص بك والبقاء على اطلاع دائم بخوارزميات محرك البحث، ويمكنك الحفاظ على تصنيفات البحث الخاصة بك وتحسينها بمرور الوقت.",
    itemIcon1: <img className="w-full h-full" src={credibilityWork} alt="Credibility Work" />,
    itemIcon2: <img className="w-full h-full" src={increasesTraffic} alt="Increases Traffic" />,
    itemIcon3: <img className="w-full h-full" src={brandAwareness} alt="brandAwareness" />,
    itemIcon4: <img className="w-full h-full" src={userExperience} alt="userExperience" />,
    itemIcon5: <img className="w-full h-full" src={Sales} alt="Sales" />,
    itemIcon6: <img className="w-full h-full" src={Strategy} alt="Strategy" />,
    itemIcon7: <img className="w-full h-full" src={localEfforts} alt="improve local Efforts" />,
    itemIcon8: <img className="w-full h-full" src={longSuccess} alt="Long Success" />,
    "reMaintenanceService": "Maintenance",
    "reMaintenanceService_ar": "صيانة",
  },
  {
    id: "productsPhotography",
    "checkTitle": "products photography services:",
    "checkTitle_ar": "خدمات تصوير المنتجات",
    "primaryItem": "Increases Sales and Conversion Rates:",
    "primaryItem_ar": "زيادة معدلات المبيعات والتحويل:",
    "secondaryItem": "I create attractive images that create more attractive offers, attract more clicks, and boost sales through increased visibility. When customers can see detailed, attractive images of your products, they're more likely to be enticed to make a purchase.",
    "secondaryItem_ar": "بعمل على نشاء  صور جذابة تقوم  بإنشاء عروض أكثر جاذبية، وتجذب المزيد من النقرات، وتعزز المبيعات من خلال زيادة الرؤية. عندما يتمكن العملاء من رؤية صور مفصلة وجذابة لمنتجاتك، فمن المرجح أن يتم إغراءهم بإجراء عملية شراء.",
    "primaryItem2": "I Help Customers Make Informed Decisions:",
    "primaryItem2_ar": "بساعد العملاء على اتخاذ قرارات مستنيرة:",
    "secondaryItem2": "Based on good product photography, i can draw customers' attention to your products and distances them from the competition. This helps customers choose from a wide range of similar products, especially on online shopping platforms like Amazon.",
    "secondaryItem2_ar": "اعتمادا على التصوير الفوتوغرافي الجيد للمنتجات بصرف انتباه العملاء إلى منتجاتك وببعدهم عن المنافسة. وذالك يساعد العملاء على الاختيار من بين مجموعة واسعة من المنتجات المماثلة، خاصة على منصات التسوق عبر الإنترنت مثل أمازون.",
    "primaryItem3": "Enhances User Experience:",
    "primaryItem3_ar": "يعزز تجربة المستخدم:",
    "secondaryItem3": "I create high-quality images that make the consumer feel in complete control and transform them from passive scrollers into active participants in the shopping experience. When customers can see detailed, visually appealing images, they can better understand the product and its features, leading to a more satisfying user experience.",
    "secondaryItem3_ar": "بقوم بإنشاء صور عالية الجودة تجعل المستهلك يشعر بالتحكم الكامل وتحوله من أدوات التمرير السلبية إلى مشاركين نشطين في تجربة التسوق. عندما يتمكن العملاء من رؤية صور مفصلة وجذابة بصريًا، يمكنهم فهم المنتج وميزاته بشكل أفضل، مما يؤدي إلى تجربة مستخدم أكثر إرضاءً.",
    "primaryItem4": "Provides Consistency:",
    "primaryItem4_ar": "يوفر الاتساق:",
    "secondaryItem4": "I use a white background to photograph products, which makes potential buyers feel that what they see is reliable and trustworthy. Consistency in product images helps create a cohesive and professional brand image.",
    "secondaryItem4_ar": "بستخدم ​​خلفية بيضاء لتصوير المنتجات، مما يجعل المشترين المحتملين يشعرون بأن ما يرونه موثوق وجدير بالثقة. يساعد الاتساق في صور المنتج في إنشاء صورة علامة تجارية متماسكة واحترافية.",
    "primaryItem5": "Reduces the Need for Ad Copy:",
    "primaryItem5_ar": "يقلل من الحاجة إلى نسخة الإعلان:",
    "secondaryItem5": "I play a crucial role in conveying information about the product, its features, and its benefits. Detailed and informative product photos can communicate vital information without relying heavily on text-based descriptions.",
    "secondaryItem5_ar": "بلعب ​​دورًا حاسمًا في نقل المعلومات حول المنتج وميزاته وفوائده. يمكن لصور المنتج التفصيلية والغنية بالمعلومات أن تنقل معلومات حيوية دون الاعتماد بشكل كبير على الأوصاف النصية.",
    "primaryItem6": "Boosts eCommerce Sales:",
    "primaryItem6_ar": "يعزز مبيعات التجارة الإلكترونية:",
    "secondaryItem6": "I help customers see what they're buying and make them more confident in their purchase decisions. In the competitive eCommerce market, visually appealing product photography can give your business a competitive edge and increase sales.",
    "secondaryItem6_ar": "بساعد ​​العملاء على رؤية ما يشترونه ويجعلهم أكثر ثقة في قرارات الشراء الخاصة بهم. في سوق التجارة الإلكترونية التنافسي، يمكن لتصوير المنتجات الجذاب أن يمنح عملك ميزة تنافسية ويزيد من المبيعات.",
    "primaryItem7": "Lighting:",
    "primaryItem7_ar": "الإضاءة:",
    "secondaryItem7": "I depend on appropriate lighting to capture high-quality photos of the product. Natural light or diffused light from soft boxes can help eliminate harsh shadows and create a more uniform and pleasing lighting setup.",
    "secondaryItem7_ar": 'بعتمد على الإضاءة المناسبة لالتقاط صور عالية الجودة للمنتج. يمكن أن يساعد الضوء الطبيعي أو الضوء المنتشر من الصناديق الناعمة في التخلص من الظلال القاسية وإنشاء إعداد إضاءة أكثر اتساقًا وإمتاعًا.',
    "primaryItem8": "Camera and Equipment:",
    "primaryItem8_ar": "الكاميرا والمعدات:",
    "secondaryItem8": "Through professional camera equipment, i can improve the quality of your product images.",
    "secondaryItem8_ar": "من خلال معدات الكاميرا الاحترافية ممكن احسن جودة صور منتجك.",
    itemIcon1: <img className="w-full h-full" src={salesRates} alt="Sales Rates" />,
    itemIcon2: <img className="w-full h-full" src={informedDecisions} alt="Informed Decisions" />,
    itemIcon3: <img className="w-full h-full" src={EnhancesExperience} alt="EnhancesExperience" />,
    itemIcon4: <img className="w-full h-full" src={ProvideConsistency} alt="ProvideConsistency" />,
    itemIcon5: <img className="w-full h-full" src={ReducesCopy} alt="ReducesCopy" />,
    itemIcon6: <img className="w-full h-full" src={eCommerceSales} alt="eCommerceSales" />,
    itemIcon7: <img className="w-full h-full" src={Lighting} alt="Lighting" />,
    itemIcon8: <img className="w-full h-full" src={CameraEquipment} alt="CameraEquipment" />,
    "reMaintenanceService": "Maintenance",
    "reMaintenanceService_ar": "صيانة",
},
  {
    id: "graphicDesigning",
    "checkTitle": "graphic designing services:",
    "checkTitle_ar": "خدمات تصميم الجرافيك",
    "primaryItem": "Professional Growth for your company:",
    "primaryItem_ar": "النمو المهني لشركتك:",
    "secondaryItem": 'I ensure you continue to grow and constantly stay up to date with the latest design practices, software updates and technological advancements.',
    "secondaryItem_ar": "بضمن لك  النمو المستمر والبقاء على اطلاع بأحدث ممارسات التصاميم باستمرار وتحديثات البرامج والتقدم التكنولوجي.",
    "primaryItem2": "Recognition and Impact:",
    "primaryItem2_ar": "الاعتراف والتأثير:",
    "secondaryItem2": "Whether it's creating a memorable logo, designing an eye-catching ad, or developing a visually appealing website, I can leave a lasting good impression on viewers and clients with graphic designs.",
    "secondaryItem2_ar": "ممكن ان اترك انطباعًا جيدا دائمًا لدى المشاهدين والعملاء عن طريق تصميمات رسومية سواء كان ذلك إنشاء شعار لا يُنسى، أو تصميم إعلان ملفت للنظر، أو تطوير موقع ويب جذاب بصريًا.",
    "primaryItem3": "Branding and Consistency:",
    "primaryItem3_ar": "العلامة التجارية والاتساق:",
    "secondaryItem3": "I build trust and recognition among users by creating and maintaining a consistent brand identity across the website. And create logos, icons, and other visual elements that represent the brand's personality and values.",
    "secondaryItem3_ar": "بقوم ببناء الثقة والتقدير بين المستخدمين عن طريق إنشاء هوية علامة تجارية متسقة والحفاظ عليها عبر موقع الويب. وإنشاء الشعارات والأيقونات والعناصر المرئية الأخرى التي تمثل شخصية العلامة التجارية وقيمها.",
    "primaryItem4": "Enhanced Communication:",
    "primaryItem4_ar": "تعزيز الاتصالات:",
    "secondaryItem4": "I present the information in a visually attractive and easy-to-understand manner. Well-designed materials such as brochures, infographics, and websites can attract and engage customers, and convey messages more effectively.",
    "secondaryItem4_ar": "يقوم بتقديم المعلومات بطريقة جذابة بصريًا وسهلة الفهم. يمكن للمواد المصممة جيدًا مثل الكتيبات والرسوم البيانية ومواقع الويب جذب العملاء وإشراكهم، ونقل الرسائل بشكل أكثر فعالية.",
    "primaryItem5": "Differentiation from competitors:",
    "primaryItem5_ar": "التمايز عن المنافسين:",
    "secondaryItem5": "I help companies differentiate themselves from their competitors by creating designs that make the company stand out using eye-catching colors, unique design elements, and effective layouts.",
    "secondaryItem5_ar": "بساعد الحل المعدل الشركات على تمييز نفسها عن منافسيها عن طريق إنشاء تصميمات تجعل الشركة متميزة  باستخدام الألوان الجذابة وعناصر التصميم الفريدة والتخطيطات الفعالة.",
    "primaryItem6": "Increased Engagement:",
    "primaryItem6_ar": "زيادة المشاركة:",
    "secondaryItem6": "Eye-catching and visually appealing designs are more likely to grab the attention of customers and engage them with the company's content. This can lead to increased customer engagement, interaction, and ultimately, conversions.",
    "secondaryItem6_ar": "من المرجح أن تجذب التصميمات الجذابة والملفتة للنظر انتباه العملاء وتجذبهم إلى محتوى الشركة. يمكن أن يؤدي هذا إلى زيادة مشاركة العملاء وتفاعلهم وفي النهاية التحويلات.",
    "primaryItem7": "Cost and Time Savings:",
    "primaryItem7_ar": "توفير التكلفة والوقت:",
    "secondaryItem7": "I can save companies time and money in the long run. Well-designed materials are more likely to be effective and require fewer revisions, reducing the need for costly redesigns.",
    "secondaryItem7_ar": "ممكن أن اوفر ​​الوقت والمال للشركات على المدى الطويل. من المرجح أن تكون المواد المصممة جيدًا فعالة وتتطلب مراجعات أقل، مما يقلل الحاجة إلى عمليات إعادة تصميم مكلفة.",
    "primaryItem8": "Flexibility and Adaptability:",
    "primaryItem8_ar": "المرونة والقدرة على التكيف:",
    "secondaryItem8": "I allow companies to adapt their visual assets to different mediums and platforms, such as print, digital, and social media. This flexibility enables companies to maintain a consistent brand image across various channels.",
    "secondaryItem8_ar": "اسمح للشركات بتكييف أصولها المرئية مع الوسائط والمنصات المختلفة، مثل الوسائط المطبوعة والرقمية ووسائل التواصل الاجتماعي. تتيح هذه المرونة للشركات الحفاظ على صورة متسقة للعلامة التجارية عبر القنوات المختلفة.",
    itemIcon1: <img className="w-full h-full" src={ProfessionalGrowth} alt="Professional Growth" />,
    itemIcon2: <img className="w-full h-full" src={RecognitionImpact} alt="Recognition Impact" />,
    itemIcon3: <img className="w-full h-full" src={BrandingConsistency} alt="Branding Consistency" />,
    itemIcon4: <img className="w-full h-full" src={EnhancedCommunication} alt="Enhanced Communication" />,
    itemIcon5: <img className="w-full h-full" src={DifferentiationCompetitors} alt="Differentiation Competitors" />,
    itemIcon6: <img className="w-full h-full" src={IncreasedEngagement} alt="Increased Engagement" />,
    itemIcon7: <img className="w-full h-full" src={CostTime} alt="Cost, Time" />,
    itemIcon8: <img className="w-full h-full" src={FlexibilityAdaptability} alt="Flexibility Adaptability" />,
    "reMaintenanceService": "Maintenance",
    "reMaintenanceService_ar": "صيانة",
    },
  {
    id: "contentCreating",
    "checkTitle": "Content creating services:",
    "checkTitle_ar": "خدمت صناعة المحتوى:",
    "primaryItem": "Identify your target audience:",
    "primaryItem_ar": "تحديد جمهورك المستهدف:",
    "secondaryItem": 'I understand who your content is targeting and what their needs and interests are.',
    "secondaryItem_ar": "بقوم بفهم من يستهدف المحتوى الخاص بك وما هي احتياجاتهم واهتماماتهم.",
    "primaryItem2": "Research and generate ideas:",
    "primaryItem2_ar": "البحث وتوليد الأفكار:",
    "secondaryItem2": "I conduct research to gather information and insights that will help generate relevant and valuable content ideas.",
    "secondaryItem2_ar": "بقوم بإجراء بحث لجمع المعلومات والرؤى التي ستساعد على إنشاء أفكار محتوى ذات صلة وقيمة.",
    "primaryItem3": "Develop content:",
    "primaryItem3_ar": "تطوير المحتوى:",
    "secondaryItem3": "I use the collected information and ideas to create content that matches your target audience's preferences and addresses their pain points.",
    "secondaryItem3_ar": "بقوم باستخدم المعلومات والأفكار المجمعة لإنشاء محتوى يتوافق مع تفضيلات جمهورك المستهدف ويعالج نقاط الضعف لديهم.",
    "primaryItem4": "Increase brand awareness:",
    "primaryItem4_ar": "زيادة الوعي بالعلامة التجارية:",
    "secondaryItem4": "I increase brand visibility and awareness by consistently creating and sharing valuable content.",
    "secondaryItem4_ar": "بقوم بزيادة رؤية العلامة التجارية والوعي بها من خلال إنشاء محتوى قيم ومشاركته باستمرار. ",
    "primaryItem5": "Building customer relationships:",
    "primaryItem5_ar": "بناء العلاقات مع العملاء:",
    "secondaryItem5": "I can build trust, loyalty and long-term relationships with its customers. By constantly providing valuable content.",
    "secondaryItem5_ar": " بقوم ببناء الثقة والولاء والعلاقات طويلة الأمد مع عملائها. من خلال تقديم محتوى قيم باستمرار.",
    "primaryItem6": "Differentiating from Competitors:",
    "primaryItem6_ar": "التمييز بين المنافسين:",
    "secondaryItem6": "I create unique and valuable content that sets the company apart from its competitors by providing insights, expertise and standing out in the market.",
    "secondaryItem6_ar": "بقوم بإنشاء محتوى فريد وقيم يميز الشركة عن منافسيها من خلال تقديم رؤى وخبرات  والتميز في السوق.",
    "primaryItem7": "Reuse and Recycle Content:",
    "primaryItem7_ar": "إعادة استخدام المحتوى وإعادة تدويره:",
    "secondaryItem7": "I can re-maintain and reuse content and this allows businesses to maximize the value of their content and reach a wider audience without starting from scratch each time.",
    "secondaryItem7_ar": 'بقوم بإعادة صيانة واستخدام المحتوى وهذا يتيح للشركات تعظيم قيمة محتواها والوصول إلى جمهور أوسع دون البدء من الصفر في كل مرة.',
    "primaryItem8": "Cost-Effective Marketing Strategy:",
    "primaryItem8_ar": "استراتيجية تسويق فعالة من حيث التكلفة:",
    "secondaryItem8": "I can create cost-effective strategic content marketing compared to traditional advertising methods. It allows businesses to reach a wider audience without large advertising expenditures, especially when leveraging digital platforms and social media.",
    "secondaryItem8_ar": 'بقوم بإنشاء محتوى استراتيجي تسويقي فعال من حيث التكلفة مقارنة بطرق الإعلان التقليدية. فهو يسمح للشركات بالوصول إلى جمهور أوسع دون نفقات إعلانية كبيرة، خاصة عند الاستفادة من المنصات الرقمية ووسائل التواصل الاجتماعي.',
    itemIcon1: <img className="w-full h-full" src={IdentifyAudience} alt="IdentifyAudience" />,
    itemIcon2: <img className="w-full h-full" src={generateIdeas} alt="generateIdeas" />,
    itemIcon3: <img className="w-full h-full" src={DevelopContent} alt="DevelopContent" />,
    itemIcon4: <img className="w-full h-full" src={IncreaseAwareness} alt="IncreaseAwareness" />,
    itemIcon5: <img className="w-full h-full" src={BuildingRelationships} alt="BuildingRelationships" />,
    itemIcon6: <img className="w-full h-full" src={DifferentiationCompetitors} alt="DifferentiationCompetitors" />,
    itemIcon7: <img className="w-full h-full" src={ReuseContent} alt="Reuse and Recycle Content" />,
    itemIcon8: <img className="w-full h-full" src={CostStrategy} alt="CostStrategy" />,
    "reMaintenanceService": "Maintenance",
    "reMaintenanceService_ar": "صيانة",
  },
  {
    id: "SponsoredAds",
    "checkTitle": "Sponsored ads services:",
    "checkTitle_ar": "خدمات الإعلانات الممولة:",
    "primaryItem": "Increase customer base and acquisition:",
    "primaryItem_ar": "زيادة قاعدة العملاء والاكتساب:",
    "secondaryItem": 'through sponsored ads i can help businesses grow their customer base and acquire new customers by targeting specific products or categories and interacting with potential customers.',
    "secondaryItem_ar": "ممكن  من خلال الإعلانات المدعومة أن اساعد الشركات على تنمية قاعدة عملائها واكتساب عملاء جدد من خلال استهداف منتجات أو فئات معينة والتفاعل مع العملاء المحتملين.",
    "primaryItem2": "Higher Conversion Rates:",
    "primaryItem2_ar": "معدلات تحويل أعلى:",
    "secondaryItem2": "I has the potential to unlock greater audience reach and increase conversion rates for brands selling on digital marketplaces with sponsored ads.",
    "secondaryItem2_ar": "بتمتع بالقدرة على فتح نطاق وصول أكبر للجمهور وزيادة معدلات التحويل للعلامات التجارية التي تبيع في الأسواق الرقمية الإعلانات المدعومة.",
    "primaryItem3": "Improved Performance:",
    "primaryItem3_ar": "أداء محسّن:",
    "secondaryItem3": "to sponsored display ads i tend to perform better than typical display ads. To increase your click-through rate.",
    "secondaryItem3_ar": "بميل ​​للإعلانات الصورية المدعومة إلى تحقيق أداء أفضل من الإعلانات الصورية النموذجية. لزيادة نسبة النقر إلى الظهور.",
    "primaryItem4": "Direct Audience Approach:",
    "primaryItem4_ar": "نهج الجمهور المباشر:",
    "secondaryItem4": "I provide a great opportunity for brands to connect with their audience directly without the need for large intermediaries, allowing for more direct communication and engagement.",
    "secondaryItem4_ar": "بوفر فرصة رائعة للعلامات التجارية للتواصل مع جمهورها مباشرة دون الحاجة إلى وسطاء كبار، مما يسمح بمزيد من التواصل والمشاركة المباشرة.",
    "primaryItem5": "Measure and analyze performance:",
    "primaryItem5_ar": "قياس وتحليل الأداء:",
    "secondaryItem5": "I measure businesses' performance to evaluate their effectiveness and analyzes metrics such as click-through rates, conversions, and return on investment (ROI) to optimize their advertising campaigns.",
    "secondaryItem5_ar": "بقوم بقياس أداء الشركات لتقييم فعاليتها و تحليل مقاييس مثل نسب النقر إلى الظهور والتحويلات وعائد الاستثمار (ROI) لتحسين حملاتهم الإعلانية.",
    "primaryItem6": "Sponsored Video Ads:",
    "primaryItem6_ar": "إعلانات الفيديو المدعومة:",
    "secondaryItem6": "I create sponsored video ads on different platforms, such as social media or video streaming sites.",
    "secondaryItem6_ar": "بقوم بصناعة إعلانات الفيديو المدعومة على منصات مختلفة، مثل وسائل التواصل الاجتماعي أو مواقع بث الفيديو.",
    "primaryItem7": "Boosting Company Image:",
    "primaryItem7_ar": "تعزيز صورة الشركة:",
    "secondaryItem7": "I help event sponsorships, a form of sponsored advertising, boost the company's image. By supporting events that align with their values ​​and target audience, companies can enhance their reputation and create positive associations with their brand.",
    "secondaryItem7_ar": 'بساعد على رعاية الأحداث، وهي شكل من أشكال الإعلانات المدعومة، في تعزيز صورة الشركة. ومن خلال دعم الأحداث التي تتماشى مع قيمها وجمهورها المستهدف، يمكن للشركات تعزيز سمعتها وإنشاء ارتباطات إيجابية مع علامتها التجارية.',
    "primaryItem8": "Trust and credibility:",
    "primaryItem8_ar": "الثقة والمصداقية:",
    "secondaryItem8": "I build trust and credibility for the company through sponsored content that is often viewed as more trustworthy than traditional advertising, especially by younger generations. This trust can lead to increased engagement and increased likelihood of conversion.",
    "secondaryItem8_ar": "ببني الثقة والمصداقية للشركة من خلال المحتوى المدعوم غالبًا ما يُنظر إليه على أنه أكثر جدارة بالثقة من الإعلانات التقليدية، خاصة من قبل الأجيال الشابة. يمكن أن تؤدي هذه الثقة إلى زيادة المشاركة وزيادة احتمال التحويل.",
    itemIcon1: <img className="w-full h-full" src={IncreaseAcquisition} alt="IncreaseAcquisition" />,
    itemIcon2: <img className="w-full h-full" src={HigherConversion} alt="HigherConversion" />,
    itemIcon3: <img className="w-full h-full" src={ImprovedPerformance} alt="ImprovedPerformance" />,
    itemIcon4: <img className="w-full h-full" src={DirectAudience} alt="DirectAudience" />,
    itemIcon5: <img className="w-full h-full" src={MeasurePerformance} alt="MeasurePerformance" />,
    itemIcon6: <img className="w-full h-full" src={SponsoredVideo} alt="SponsoredVideo" />,
    itemIcon7: <img className="w-full h-full" src={BoostingImage} alt="BoostingImage" />,
    itemIcon8: <img className="w-full h-full" src={TrustCredibility} alt="TrustCredibility" />,
    "reMaintenanceService": "Maintenance",
    "reMaintenanceService_ar": "صيانة",
  },
]
export default items